version: '3.5'

services:
  etcd:
    image: quay.io/coreos/etcd:latest
    command: etcd -listen-peer-urls=http://127.0.0.1:2380 -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-advertise-peer-urls=http://127.0.0.1:2380 --initial-cluster default=http://127.0.0.1:2380
    networks:
      - milvus

  pulsar:
    image: apachepulsar/pulsar:latest
    command: bin/pulsar standalone
    networks:
      - milvus

  minio:
    image: minio/minio:RELEASE.2020-12-03T00-03-10Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - milvus

  master:
    image: registry.zilliz.com/milvus/milvus:master-release
    command: ["/milvus/bin/milvus", "run", "master"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      PULSAR_ADDRESS: pulsar://pulsar:6650
      DATA_SERVICE_ADDRESS: dataservice:13333
      INDEX_SERVICE_ADDRESS: indexservice:31000
      QUERY_SERVICE_ADDRESS: queryservice:19531
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"
    networks:
      - milvus

  proxynode:
    image: registry.zilliz.com/milvus/milvus:master-release
    command: ["/milvus/bin/milvus", "run", "proxynode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      PULSAR_ADDRESS: pulsar://pulsar:6650
      MASTER_ADDRESS: master:53100
      DATA_SERVICE_ADDRESS: dataservice:13333
      INDEX_SERVICE_ADDRESS: indexservice:31000
      QUERY_SERVICE_ADDRESS: queryservice:19531
    ports:
      - "19530:19530"
    networks:
      - milvus

  queryservice:
    image: registry.zilliz.com/milvus/milvus:master-release
    command: ["/milvus/bin/milvus", "run", "queryservice"]
    environment:
      MASTER_ADDRESS: master:53100
      DATA_SERVICE_ADDRESS: dataservice:13333
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"
    networks:
      - milvus

  querynode:
    image: registry.zilliz.com/milvus/milvus:master-release
    command: ["/milvus/bin/milvus", "run", "querynode"]
    environment:
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      MASTER_ADDRESS: master:53100
      DATA_SERVICE_ADDRESS: dataservice:13333
      INDEX_SERVICE_ADDRESS: indexservice:31000
      QUERY_SERVICE_ADDRESS: queryservice:19531
      QUERY_NODE_ID: 1
    depends_on:
      - "queryservice"
    networks:
      - milvus

  indexservice:
    image: registry.zilliz.com/milvus/milvus:master-release
    command: ["/milvus/bin/milvus", "run", "indexservice"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MASTER_ADDRESS: master:53100
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"
    networks:
      - milvus

  indexnode:
    image: registry.zilliz.com/milvus/milvus:master-release
    command: ["/milvus/bin/milvus", "run", "indexnode"]
    environment:
      MINIO_ADDRESS: minio:9000
      INDEX_SERVICE_ADDRESS: indexservice:31000
    depends_on:
      - "indexservice"
    networks:
      - milvus

  dataservice:
    image: registry.zilliz.com/milvus/milvus:master-release
    command: ["/milvus/bin/milvus", "run", "dataservice"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      MASTER_ADDRESS: master:53100
    depends_on:
      - "etcd"
      - "pulsar"
      - "minio"
    networks:
      - milvus

  datanode:
    image: registry.zilliz.com/milvus/milvus:master-release
    command: ["/milvus/bin/milvus", "run", "datanode"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      PULSAR_ADDRESS: pulsar://pulsar:6650
      MASTER_ADDRESS: master:53100
      DATA_SERVICE_ADDRESS: dataservice:13333
    depends_on:
      - "dataservice"
    networks:
      - milvus

networks:
  milvus:
